# Generated by Django 6.0.1 on 2026-01-23 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounting', '0001_initial'),
        ('housekeeping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='related_maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='housekeeping.maintenancerequest'),
        ),
    ]
