# Generated by Django 6.0.1 on 2026-01-23 21:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='amenity name')),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('entertainment', 'Entertainment'), ('comfort', 'Comfort'), ('safety', 'Safety'), ('bathroom', 'Bathroom'), ('other', 'Other')], default='other', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'amenity',
                'verbose_name_plural': 'amenities',
                'db_table': 'amenities',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='room type name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='base price per night')),
                ('weekend_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='weekend price per night')),
                ('max_adults', models.PositiveIntegerField(default=2)),
                ('max_children', models.PositiveIntegerField(default=2)),
                ('max_occupancy', models.PositiveIntegerField(default=4)),
                ('size_sqm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='size in square meters')),
                ('primary_image', models.URLField(blank=True, max_length=500)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'room type',
                'verbose_name_plural': 'room types',
                'db_table': 'room_types',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='room_types_slug_e4d33a_idx'), models.Index(fields=['is_featured', 'display_order'], name='room_types_is_feat_12d4ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='room_management.roomtype')),
            ],
            options={
                'verbose_name': 'room image',
                'verbose_name_plural': 'room images',
                'db_table': 'room_images',
                'ordering': ['room_type', 'display_order'],
                'indexes': [models.Index(fields=['room_type', 'is_primary'], name='room_images_room_ty_f76561_idx')],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('room_number', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='room number')),
                ('floor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='floor number')),
                ('building', models.CharField(blank=True, max_length=50)),
                ('has_view', models.BooleanField(default=False, verbose_name='has view')),
                ('view_type', models.CharField(blank=True, help_text='e.g., Sea View, City View, Garden View', max_length=50)),
                ('has_balcony', models.BooleanField(default=False, verbose_name='has balcony')),
                ('is_accessible', models.BooleanField(default=False, verbose_name='wheelchair accessible')),
                ('current_status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('cleaning', 'Cleaning'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved'), ('out_of_order', 'Out of Order')], db_index=True, default='available', max_length=20)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='room_management.roomtype')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'db_table': 'rooms',
                'ordering': ['room_number'],
                'indexes': [models.Index(fields=['room_type', 'current_status', 'is_active'], name='rooms_room_ty_3b2113_idx'), models.Index(fields=['floor', 'building'], name='rooms_floor_8f7ad1_idx')],
                'constraints': [models.UniqueConstraint(fields=('room_number', 'is_active'), name='unique_active_room_number')],
            },
        ),
        migrations.CreateModel(
            name='RoomTypeAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complimentary', models.BooleanField(default=True)),
                ('additional_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='room_management.amenity')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_amenities', to='room_management.roomtype')),
            ],
            options={
                'verbose_name': 'room type amenity',
                'verbose_name_plural': 'room type amenities',
                'db_table': 'room_type_amenities',
                'unique_together': {('room_type', 'amenity')},
            },
        ),
    ]
