# Generated by Django 6.0.1 on 2026-01-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='activity_lo_user_id_e40ffe_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='activity_lo_model_n_8ff728_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='activity_lo_action__4f011a_idx',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
