# Generated by Django 5.2.6 on 2025-09-09 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authontication', '0002_customuser_is_verified_customuser_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='user',
        ),
    ]
