# Generated by Django 5.0.6 on 2025-03-18 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking_api.roomtype'),
            preserve_default=False,
        ),
    ]
