# Generated by Django 5.0.6 on 2025-03-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_room',
        ),
    ]
