# Generated by Django 5.0.6 on 2025-04-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0002_remove_booking_booking_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_type']},
        ),
    ]
