# Generated by Django 5.0.6 on 2025-03-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0003_alter_roomimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='image',
        ),
    ]
