# Generated by Django 5.0.6 on 2025-04-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0004_alter_room_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
