# Generated by Django 5.0.6 on 2025-04-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0005_delete_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='icon',
        ),
    ]
