# Generated by Django 5.2.6 on 2025-09-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0006_remove_amenity_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
